//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mooder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mooder.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album name.
        /// </summary>
        public static string AlbumName {
            get {
                return ResourceManager.GetString("AlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album picture.
        /// </summary>
        public static string AlbumPicture {
            get {
                return ResourceManager.GetString("AlbumPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyric.
        /// </summary>
        public static string Lyric {
            get {
                return ResourceManager.GetString("Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide lyric.
        /// </summary>
        public static string LyricHide {
            get {
                return ResourceManager.GetString("LyricHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lyric.
        /// </summary>
        public static string LyricShow {
            get {
                return ResourceManager.GetString("LyricShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music sources.
        /// </summary>
        public static string MusicSources {
            get {
                return ResourceManager.GetString("MusicSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide playlist.
        /// </summary>
        public static string PlaylistHide {
            get {
                return ResourceManager.GetString("PlaylistHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show playlist.
        /// </summary>
        public static string PlaylistShow {
            get {
                return ResourceManager.GetString("PlaylistShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat all.
        /// </summary>
        public static string RepeatAll {
            get {
                return ResourceManager.GetString("RepeatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repeat.
        /// </summary>
        public static string RepeatNone {
            get {
                return ResourceManager.GetString("RepeatNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track name.
        /// </summary>
        public static string TrackName {
            get {
                return ResourceManager.GetString("TrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full volume.
        /// </summary>
        public static string VolumeFull {
            get {
                return ResourceManager.GetString("VolumeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute volume.
        /// </summary>
        public static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
    }
}
